### ISSUE TITLE
Wrong order of the properties in ore:Aggregation

### ISSUE THREAD

**Issue by JIwanowa** [DM2E/dm2e-mappings#100]
The order of the properties in ore:Aggregation seems to be wrong. The right one here isn't an alphabetical like in edm:ProvidedCHO but this:
1. edm:aggregatedCHO  
2. edm:dataProvider  
3. edm:hasView
4. edm:isShownAt
5. edm:object
6. edm:preview
7. edm:provider
8. dc:rights
9. edm:rights 
(defined in the ORE.xsd within the EDM.xsd)

**Comment by kba** [comment]
For reference, the section mentioned by @JIwanowa reads

```
    <extension base="rdf:AboutType">
                    <sequence>
                        <element ref="edm:aggregatedCHO" maxOccurs="1" minOccurs="1"/>
                        <element ref="edm:dataProvider" maxOccurs="1" minOccurs="0"/>
                        <element ref="edm:hasView" maxOccurs="unbounded" minOccurs="0"/>
                        <element ref="edm:isShownAt" maxOccurs="1" minOccurs="0"/>
                        <element ref="edm:isShownBy" maxOccurs="1" minOccurs="0"/>
                        <element ref="edm:object" maxOccurs="1" minOccurs="0"/>
                        <element ref="edm:provider" maxOccurs="1" minOccurs="1"/>
                        <element ref="dc:rights" maxOccurs="unbounded" minOccurs="0"/>
                        <element ref="edm:rights" maxOccurs="1" minOccurs="0"/>
                        <element ref="edm:ugc" maxOccurs="1" minOccurs="0"/>
                    </sequence>
```

(https://github.com/europeana/corelib/blob/master/corelib-solr-definitions/src/main/resources/eu/ORE.xsd)

Hence, we will only emit statements about an Aggregation with exactly those properties in exactly this order (repetitions are okay, except for `edm:provider` and `edm:aggregatedCHO`). Since there were no errors about this so far, I assume that we don't have any properties in DM2E beyond those listed.

Will fix the sorting XSD.

**Comment by kba** [comment]
leaving this open until tested.

**Comment by kba** [comment]
This is was fixed by https://github.com/DM2E/dm2e-ontologies/commit/c9add5e9c6d3735c71be211781a59a538c71107c
