### ISSUE TITLE
dm2e:displayLevel="true"^^xsd:boolean should imply the existence of dc:title

### ISSUE THREAD

**Issue by kba** [DM2E/dm2e-mappings#11]
Everything that should show up in the search results should have a title.

**Comment by ksdm2e** [comment]
At frist, that's a question for a search engine not for a data model for describing cultural data. IMHO, it's up to the consuming application to deal with such an issue.

There is already a solution for that: regarding EDM, the authors of the model estimated the situation correctly, that not every CHO has a title. Especially in archival description data, there is very often no such thing as title, because archival documents are not evaluated and described from this perspective.

Thatswhy, they provided the opportunity to choose between title or description (or something more). 

An consuming application should consider this.

**Comment by kba** [comment]
What should be in the title field of a search engine result. Please give an example of a CHO that should be displayed in search results (displayLevel true) but has no title.

What should be this client-side mechanism? Should I display the start of the description as the title? Should it be called "Untitled CHO"?

**Comment by ksdm2e** [comment]
the start of description was also my first guess.

Can we investigate examples from the ingested data?

**Comment by kba** [comment]
Actually, I can't find any at the moment using this query: https://github.com/DM2E/dm2e-ontologies/blob/master/src/main/resources/sparql-queries/display-level-true-no-title.rq If anyone has an example, please share
