### ISSUE TITLE
How to handle bibo:number for CHOs that don't have them?

### ISSUE THREAD

**Issue by kba** [DM2E/dm2e-mappings#13]
`bibo:number` is mandatory and has datatype `xsd:int`.

When mapping encounters a page without a page number what should data providers set as a value here. They must set some value and it must be a number.

Probably `-1` is a good idea though this will break the naive find-the-first-page algorithm.

Otherwise `bibo:number` should not be mandatory.

**Comment by d0rg0ld** [comment]
I am wondering if it is really possible for such a situation to happen. Usually (AFAIK) page information is stored in some dedicated structure such as a METS file where pages are listed in the order they were scanned, regardless of having a page numner or not. I guess that this applies to other forms of representing structural data as well. Are there any examples from content providers having the structural information of a digitised item without any, at least, implicit order?

**Comment by ksdm2e** [comment]
bibo:number cannot be mandatory. It should be recommended.

**Comment by d0rg0ld** [comment]
I recently proposed that bibo:number should be mandatory whenever edm:isNextInSequence is used. This makes sense to me. There must be, however, some order in the pages (otherwise annotation would be painful) and the provider should take care of this. Do you have problems with extracting the ordering of your pages?

**Comment by kba** [comment]
I think HUB ran into this problem with the Dingler data.

+1 for the edm:isNextInSequence proposal.

**Comment by ksdm2e** [comment]
When edm:isNextInSequence is used, the bibo:number can be estimated with this relation. The order can be deduced as well.
Actually there is no need for bibo:number.

**Comment by d0rg0ld** [comment]
In principle yes, but sincie it is easier for a provider to normalise the isNextInSequence ordering into bibo:number values we decided to make it mandatory. It will be some effort to deduce the ordering once millions of page chos will have been ingested

**Comment by edroege** [comment]
We do not always have page numbers (sometimes we have the string NaN instead) but I think we can create numbers by using the webresources of the pages. I do not think that there is no need for bibo:number - it can make it easier to use the data. But I am not sure if it can really be mandatory. Guess we will see this when all mappings are ingested. Maybe this should not be part of the validation as it may not be possible for every provider to have a value for the property

**Comment by kba** [comment]
If it can't be guaranteed to be provided in all cases, data consumers can't rely on it being there. Hence I'd say make it strongly recommended but not mandatory to not dilute the semantics of _mandatory_.

**Comment by edroege** [comment]
I agree with Konstantin. I do also see a large difference between mandatory properties like shownAt or aggregatedCHO which are really crucial and properties like bibo:number that would be very nice to have but if someone cannot provide them, the mapping should not be invalid.

**Comment by d0rg0ld** [comment]
Dear Evelyn, with or without page numbers, pages should be in the order they have been scanned. Isn't it the case with your data? This means that you dont use isNextInSequence for pages?

**Comment by edroege** [comment]
We use isNextInSequence for pages - we can sort them via their uris. And Julia could manage to build page numbers from URIs but we have to test if this really fits. The pages are sorted but have no numbers

**Comment by d0rg0ld** [comment]
I see, thanks. In general I dont really care who sets the value for bibo:number, as Kilian mentioned before, this could very well be done in post-processing. We decided to introduce a provider mapped mandatory bibo:number in order to lower the post-processing effort. I guess that most providers would ignore this property if not mandatory ...

**Comment by ksdm2e** [comment]
We get bibo:number from a value, which  - I guess - is proofed several times during capturing:

``` xml
...
<xsl:if test="exists($thePB/@facs)">
            <xsl:variable name="pNumber" select="tei2edm:withoutLeadingZero($thePB/@facs, '#f')" as="xs:integer"/>
            <xsl:element name="bibo:number">
                <xsl:attribute name="rdf:datatype">
                    <xsl:value-of select="'http://www.w3.org/2001/XMLSchema#int'"/>
                </xsl:attribute>
                <xsl:value-of select="$pNumber"/>
            </xsl:element>
        </xsl:if>
...
    <xsl:function name="tei2edm:withoutLeadingZero" as="xs:integer">
        <xsl:param name="aString"/>
        <xsl:param name="aReplaceable"/>

        <xsl:variable name="aStringRepl" select="replace($aString, $aReplaceable, '')" />
        <xsl:choose>
            <xsl:when test="$aStringRepl castable as xs:integer">
                <xsl:value-of select="number($aStringRepl)"/>
            </xsl:when>
            <xsl:otherwise>
                <xsl:value-of select="0"/>
            </xsl:otherwise>    
        </xsl:choose>
    </xsl:function>
```

As you can see, it is actually @kba's proposal ("0" instead of "-1").

But still I vote for "strongly recommended" oder MAY, but not _mandatory_.

Further more, "mandatory" shouldn't be used to educate dataproviders, but assure data quality.

@edroege Maybe you can clarify this in the spec: bibo:number is an order number, but not the page label, e.g. III.

**Comment by knepper** [comment]
I would like to vote for removing the property. It's a redundant information - If you save the effort to generate the numbers from isNextInSequence, you will need the same effort to check the consistency of bibo:number and isNextInSequence. Otherwise, you risk to break the display later.

My vote: It's easier to calculate then to check and correct.

In general, the model should avoid redundant information for this reason.

**Comment by kba** [comment]
As of 1.1_Rev1.5 bibo:number is not mandatory anymore.
