### ISSUE TITLE
dm2e:levelOfHierarchy should be in ore:Aggregation

### ISSUE THREAD

**Issue by edroege** [DM2E/dm2e-mappings#25]
dm2e:displayLevel is in the domain or ore:Aggregation; dm2e:levelOfHierarchy should be there as well

**Comment by ksdm2e** [comment]
I also thought about that yesterday and came to the following conclusion:

As _dm2e:levelOfHierarchy_ accompanies _dcterms:isPartOf_, it should stay in _edm:ProvidedCHO_. (Although _dm2e:levelOfHierarchy_ is a very strange category)

As _dm2e:displayLevel_ is relevant for a displaying application (and not relevant for the description of the object), _ore:Aggregation_ is the right place.

**Comment by d0rg0ld** [comment]
I agree with Kilian on this issue. I also agree that since we now have mandatory displayLevel it might not be necessary to use the optional levelOfHierarchy any more ...

**Comment by edroege** [comment]
Agree. I leave the property where it is.

@d0rg0ld Therefore levelOfHierarchy is optional - the provider can use it or not. I suggest to wait for more valid mappings and how the search interfaces can handle the data before we delete the property.

**Comment by ksdm2e** [comment]
It is a good practice in programming, to set properties, which are probably not needed anymore, as _deprecated_ first. 

It is a superfluent property, so nobody will get hurt, if it's in the data.

"Deprecated" properties might also be validated with @kba's tool and noticed as "WARNING", because the immediate deletion of the property will break all current transformations. (As it is the case with dc:subject maxOccur 1 in Rev13).

**Comment by edroege** [comment]
Good idea. Will keep that also in mind when we revise all properties in the model. For now, levelOfHierarchy stays in the model without changes but if turns out that it is not used or needed, we will mark it as deprecated

**Comment by kba** [comment]
Since no changes are planned for now, I'll close this.
