### ISSUE TITLE
no dc:format data ingested (fatal error) 

### ISSUE THREAD

**Issue by chrmor** [DM2E/dm2e-mappings#46]
Example:

http://data.dm2e.eu/data/html/resourcemap/uber/dingler/page_pj022_pb150/1393515961557

there is no dc:format for the annotatable resource.

**Comment by kba** [comment]
@JIwanowa  How did you get that ingested, did you turn off validation?

**Comment by JIwanowa** [comment]
No I didn't turned any think. I just ingested the data normally and didn't get any error by the ingestion. The properties that I used are these: base = http://data.dm2e.eu/data/dataset/
provider = uber
dataset = dingler
label = Dingler Online 
use-oai-pmh = false
input = /data/INBOX/test_dingler_27_02_2014/julia-uber-dingler-rdfdata-2014-02-27-version3-only-as-test.zip
keep-temporary = false
dm2e-model-version = 1.1_Rev1.4

**Comment by JIwanowa** [comment]
Now I ingested a test dataset from dingler: http://data.dm2e.eu/data/html/dataset/uber/dingler/20140304122625645

@chrmor: Please let me know if there are some more errors! I turned off the validation, because of the [FATAL]  uses an unknown dc:type http://purl.org/spar/fabio/Article, which is actually not right. I am aware of some errors within the .../dingler/page/_pj022... and I am still working on it. I hope will be fixed today.

The input-rdf-files always contain dc:format within annotatable resources.

**Comment by kba** [comment]
The validation problem is fixed, dingler contains no errors. You can go ahead and ingest the whole thing.

**Comment by JIwanowa** [comment]
Couldn't ingest more data due to an "[FATAL]  has unsupported MIME type 'text/html'" Error. The text/html should be support at least for our data.

**Comment by kba** [comment]
lets continue this in #61
