### ISSUE TITLE
Known Bug in timespan resources: Wrong dateTime.

### ISSUE THREAD

**Issue by knepper** [DM2E/dm2e-mappings#59]
Example:

``` xml
<edm:begin
rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">1788-1800-01-01T00:00:00</edm:begin>
```

Reason: Freestyle mods data.

``` xml
<mods:dateIssued encoding="w3cdtf" keyDate="yes">1788-1800</mods:dateIssued>
```

Will be fixed by mapping - might be common.

**Comment by kba** [comment]
yes, another common violation of xsd:dateTime are literals like

```
546-02-03T00:00:00
```

note the three leasing digits. these should be left-padded with zeroes. i think this is in mpiwg/rara. 

the validator is more lenient than our triplestore at the moment. will be fixed

**Comment by d0rg0ld** [comment]
ah good to know, I will fix this for the codices

**Comment by kba** [comment]
As of buld 'Tue Mar  4 19:23:40 CET 2014', The validator will not only see if it can parse the date but also match it against the pattern

```
\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z?
```

Invalid xsd:dateTimes will show up as an error. Maybe we should even make that a fatal error since it might be a problem for downstream consumers (such as Pundit or the OAI repo)

**Comment by kthth** [comment]
@kba 
cannot find 

```
546-02-03T00:00:00
```

in rara

**Comment by kba** [comment]
@kthth Don't know if it was in rara. As these are FATAL validation errors as of https://github.com/DM2E/dm2e-ontologies/commit/384f069545152da9d44967681da11f32773d719c it doesn't matter who ingested it in the first place. They will find out when validating.
